@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US005

autonumber

actor "HRM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to generate a team proposal
    activate System

        System --> Employee : requests data (minimum and maximum number of collaborators)
    deactivate System

    Employee -> System : types data
    activate System

        System --> Employee : requests data (team members skills)
    deactivate System

    Employee -> System : selects data
    activate System

        System --> Employee : shows all data and requests confirmation
 deactivate System

       Employee -> System : confirms data
        activate System

            System --> Employee : displays operation success and shows the team
        deactivate System



@enduml