@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

class ListOfVehiclesNeedingCheckUp {
}

class Vehicle {
   brand
   model
   vehicleID
   type
   tare
   grossWeight
   currentKm
   registerDate
   acquisitionDate
   checkupFrequency
}


ListOfVehiclesNeedingCheckUp "1" - "*" Vehicle : has >

@enduml