@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods


class SystemUser {
    name
    email
    password
    phone

}


class VFM {
}

class ListOfVehiclesNeedingCheckUp {
}

class Vehicle {
   brand
   model
   vehicleID
   type
   tare
   grossWeight
   currentKm
   registerDate
   acquisitionDate
   checkupFrequency
}


ListOfVehiclesNeedingCheckUp "1" - "*" Vehicle : has >
SystemUser --|> VFM
VFM "1" - "*" ListOfVehiclesNeedingCheckUp: registers >
@enduml