@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class Job {
    - String jobName
    + Job(jobName)
    + getJobName()
    + getDescription()
}

class Repositories {


    - Repositories()
    + getInstance() : Repositories
    + getCollaboratorRepository()
    + getVehicleRepository()
    + getJobRepository()
    + getJobRepository()
    + getAuthenticationRepository()
}

class JobRepository {

    + getJobList()
    + registerJob(jobName)
    + size()
    - jobIsValid(jobName)
    - isValidJobName(jobName)
    - jobNameIsUnique(jobName)
}

class RegisterJobController {

    + RegisterJobController()
    + registerJob(jobName)
}

class HRM {}

class SystemUser {
    name
    email
    password
    phone
}

class RegisterJobUI {}

SystemUser <|-- HRM
HRM  <-- Job : registered by
RegisterJobController ..> Repositories : repositories
RegisterJobController ..> JobRepository : jobRepository
RegisterJobController ..> Job : job

RegisterJobUI .> RegisterJobController
Repositories -->"1" JobRepository
Repositories -> Repositories : instance
Job "*" <-- JobRepository

@enduml
