@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "VFM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to register a vehicle


        System --> Employee : requests data (Brand, Model, Vehicle Id; Type, \nTare,Gross Weight, Current Km, Register Date, \nAcquisition Date, Maintenance/Checkup Frequency)
    deactivate System

    Employee -> System : types the data
    activate System

        System --> Employee : requests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml