@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "FM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to register a vehicle


        System --> Employee : requests Brand, Model, Type, Tare,Gross Weight,Current Km, Register Date, Acquisition Date, Maintenance/Checkup Frequency
    deactivate System

    Employee -> System : types the Brand, Model, Type, Tare,Gross Weight, Current Km, Register Date, Acquisition Date, Maintenance/Checkup Frequency (in Kms)

    activate System

        System --> Employee : shows task category list and asks to select one
    deactivate System

    Employee -> System : selects a task category
    activate System

        System --> Employee : shows all data and requests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml