@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



participant ":CreateTeamProposalController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "skillRepository:\nSkillRepository" as SkillRepository
participant "collaboratorRepository:\nCollaboratorRepository" as CollaboratorRepository
participant "teamRepository:\nTeamRepository" as TeamRepository
autonumber 16.1
      CTRL -> PLAT : getCollaboratorRepository()
      activate PLAT
        PLAT --> CTRL : collaboratorRepository
      deactivate PLAT

      CTRL -> CollaboratorRepository : getCollaboratorsBySkills(skills)
      note right : filter collaborators\nbased on their skills
      activate CollaboratorRepository
        CollaboratorRepository --> CTRL : collaboratorList


@enduml