@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant ":CreateTeamProposalUI" as UI
participant ":CreateTeamProposalController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT

participant "teamRepository:\nTeamRepository" as TeamRepository
participant "team\n:Team" as TEAM
autonumber 3

activate CTRL
    group Get Task Category List


            CTRL -> PLAT : getTeamRepository()
                 activate PLAT
                   PLAT --> CTRL : teamRepository
                 deactivate PLAT

                 CTRL -> TeamRepository : createTeam(selectedCollaborators)
                 activate TeamRepository
                   TeamRepository -> TEAM: create(selectedCollaborators)
                   note right : team is created with a PENDING state
                   TeamRepository -> TeamRepository : addTeam()
                   TeamRepository --> CTRL : team
                 deactivate TeamRepository
                 CTRL --> UI : team


               @enduml