@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "VFM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to list the vehicles needing a check-up
    activate System

        System --> Employee : displays the vehicles that need a check-up
    deactivate System


@enduml