@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative Two

autonumber

actor "HRM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to create a new skill
    activate System

    System --> Employee : requests data (type a skill name)
    deactivate System

    Employee -> System : types skill name and confirms
    activate System



    System --> Employee : displays status of operation \nmessage (ie: "skill added to list")
    deactivate System

@enduml