
    @startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Organization Employee" as ADM
participant ":RegisterSkillsUI" as UI
participant ":RegisterSkillController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "skillsRepository:\nSkillsRepository" as skillsRepository


activate ADM

        ADM -> UI : asks to register a new skill
        activate UI
        UI --> ADM : requests
        deactivate UI
        ADM -> UI : types requested data (skill name)
        activate UI
        UI --> ADM : requests confirmation
        deactivate UI
            ADM -> UI : confirms
        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : registerSkills(skillName)
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getSkillsRepository()
                activate PLAT

                    PLAT --> CTRL: skillsRepository
                deactivate PLAT

                CTRL -> skillsRepository : registerSkill (skillName)
                activate skillsRepository

                skillsRepository -> skillsRepository : validateSkill()
                activate skillsRepository

                skillsRepository --> skillsRepository : validation result
                deactivate skillsRepository


                    skillsRepository --> CTRL : success of operation
                deactivate skillsRepository



                CTRL --> UI : success of operation
            deactivate CTRL

            UI -> UI : displaySuccessMessage()
            activate UI

            UI --> ADM : operation success message
        deactivate UI




deactivate ADM

@enduml