@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class Skill {
    - String skillName
    + Skill(skillName)
    + getName(): string
    + getDescription(): string
}

class Repositories {
    - collaboratorRepository
    - vehicleRepository
    - skillRepository
    - jobRepository

    - Repositories()
    + getInstance()
    + getCollaboratorRepository()
    + getVehicleRepository()
    + getSkillRepository()
    + getJobRepository()
}

class SkillRepository {
    - ArrayList skillList
    + SkillRepository()
    + registerSkill(skillName)
    + getSkillList()
}

class RegisterSkillController {
    - skillRepository

    + RegisterSkillController(skillRepository: SkillRepository)
    + registerNewSkill(skillName)
    + registerSkillFromFile(filePath)
    - readSkillsFromFile(filePath)
}

class HRM {}

class SystemUser {
    name
    email
    password
    phone
}

class RegisterSkillUI {}

SystemUser <|-- HRM
HRM "1" --> "*" Skill : registers
RegisterSkillController ..> Repositories : repositories

RegisterSkillUI .> RegisterSkillController
Repositories -->"1" SkillRepository
Repositories -> Repositories : instance
Skill "*" <-- "1" SkillRepository : has

@enduml
