@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Collaborator" as ADM
participant ":AgendaEntryUI" as UI
participant ":CancelAgendaEntryController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "agendaEntryRepository:\nAgendaEntryRepository" as Repo
participant "AgendaEntryMapper"
participant "AgendaEntryDTO"
participant "AgendaEntry"
participant "EntriesBetweenDatesDTO"

activate ADM

ADM -> UI : asks to consult the tasks assigned to him between two dates.
activate UI

UI -> CTRL : create
activate CTRL
CTRL -> "AgendaEntryMapper" : create
deactivate "AgendaEntryMapper"

UI --> ADM : asks for the dates he wants to search
ADM -> UI : write the desired dates

CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton

RepositorySingleton --> CTRL: repositories
deactivate RepositorySingleton

CTRL -> PLAT : getAgendaEntryRepository()
activate PLAT

PLAT --> CTRL: AgendaEntryRepository
deactivate PLAT

UI -> CTRL : getEntriesBetweenDates(date1,date2)

CTRL -> Repo : getEntriesBetweenDates()
activate Repo

Repo --> CTRL :EntriesBetweenDatesList
deactivate Repo

loop for each agendaEntry in EntriesBetweenDatesList
    "AgendaEntryMapper" -> "AgendaEntryDTO" : agendaEntryDTO = toDTO(agendaEntry)
    activate "AgendaEntryDTO"
    deactivate "AgendaEntryDTO"
end

"AgendaEntryMapper" --> CTRL : agendaEntryDTOList
deactivate "AgendaEntryMapper"

"AgendaEntryDTO" --> UI : EntriesBetweenDatesDTO
deactivate "AgendaEntryDTO"

UI --> ADM : show the list of tasks between these two dates
deactivate UI

deactivate ADM

@enduml
