@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class GreenSpace {
    - greenSpaceType
    - name
    - address
    - area
    + equals()
}

class Repositories {


    - Repositories()
    + getInstance() : Repositories
    + getCollaboratorRepository()
    + getVehicleRepository()
    + getSkillRepository()
    + getJobRepository()
    + getAuthenticationRepository()
    + getGreenSpaceRepository()
    + getTeamRepository()
    + getAgendaEntryRepository()
    + getToDoListEntryRepository()

}

class GreenSpaceRepository {
    + getGreenSpaceList()
    + registerGreenSpace(name, address, area)
    + size()
    - isUnique(greenSpace)
}

class RegisterGreenSpaceController {

    + RegisterGreenSpaceController()
    + registerGreenSpace(name, area)
    - getGreenSpaceRepository()
    - getGreenSpaceTypeList()
}

class GSM {}

class SystemUser {
    name
    email
    password
    phone
}


SystemUser <|-- GSM
GSM  <-- GreenSpace : registered by
RegisterGreenSpaceController ..> Repositories : repositories
RegisterGreenSpaceController ..> GreenSpaceRepository : greenSpaceRepository
RegisterGreenSpaceController ..> GreenSpace : greenSpace

RegisterGreenSpaceUI .> RegisterGreenSpaceController
Repositories -->"1" GreenSpaceRepository
Repositories -> Repositories : instance
GreenSpace "*" <-- GreenSpaceRepository

@enduml
