@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "VFM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to postpone an entry in the Agenda
    activate System

        System --> Employee : shows the list of entries in the Agenda and asks to\nselect one
    deactivate System

    Employee -> System : selects an entry
        activate System

            System --> Employee : shows the current date planed and asks to select\na new one
        deactivate System

        Employee -> System : selects new date for the entry
            activate System

                System --> Employee : shows information and asks confirmation
            deactivate System

            Employee -> System : confirms
                activate System

                    System --> Employee : shows message of (in)success



@enduml