@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods



class MS {
    name
    vatNumber
    website
    phoneNumber
    email

}

class GreenSpace {
    size
}

class Garden
class MediumSizedPark
class LargeSizedPark

class SystemUser {
    name
    email
    password
    phone

}
class HRM {
}
class VFM {
}
class Collaborator {
    birthdate
    admissionDate
    address
    idDocumentType
    idDocumentNumber
}
class GSM {
}
class GSU {
}

class TeamProposal {
}

class Team {
minimumSize
maximumSize
}

class Skill {
    name
}

class Job {
    name
}

class Task {
    description
    recurrency
}

class VehicleCheckup {

    date
    currentKms
}

class Vehicle {
   brand
   model
   vehicleID
   type
   tare
   grossWeight
   currentKm
   registerDate
   acquisitionDate
   checkupFrequency
}

class Machine {
    name
}

class Equipment {
    name
}

class Agenda {
}

class AgendaEntry {
    timeInterval
    date
}

class GreenSpacesUserPortal{
}

class Comment{
    description
}
class Report{
    description
}



class ToDoList{

}


SystemUser <|-- HRM
SystemUser <|-- VFM
SystemUser <|-- Collaborator
SystemUser <|-- GSM
SystemUser <|-- GSU

GreenSpace <|-- Garden
GreenSpace <|-- MediumSizedPark
GreenSpace <|-- LargeSizedPark

Task "1" -- "1..*" GreenSpace : occurs in >

Agenda "1" -- "*" AgendaEntry : has >
AgendaEntry "1" -- "1" Task : defines >
AgendaEntry "1" -- "1" Team : defines >

VFM " 1" -- "*" Vehicle : registers >
VFM "  1 " -- "*" Machine : manages >
VFM "  1    " -- "*" Equipment : manages >
Vehicle "1   " -- "0..* " VehicleCheckup : has >
VFM "1 " -- "*" VehicleCheckup : registers >
GSU"  1  " -- "0..*          " Report: makes >
GSU"  1  " -- "0..*" Comment: makes >
GSU"  1  " -- "1  " GreenSpacesUserPortal:  uses >
GreenSpacesUserPortal "1                 " -- "0..*   " Report : has >
GreenSpacesUserPortal "1    " -- "0..*" Comment : has >

MS "1" - "*" SystemUser : has >
MS "1  " - "0..*" Task: owns >
MS "1" - "*" Machine : has >
MS "1 " - "*" Vehicle : has >
MS "1" - "*" Equipment : has >

Task "1" - "1  " Team:   carried out by   >
ToDoList "1" - "0..*" Task: contains >

HRM "1 " -- "*" Collaborator : registers >
HRM "1 " -- "*" Job : creates >
HRM "1 " -- "*" Skill : creates >
HRM "1" -- "1  " TeamProposal : requests >
TeamProposal "1 " --"1 " Team: has >
Team "1 " -- "*" Collaborator: has >
Skill "1..*" - "1" Collaborator: is atributed to >
Collaborator "1 " -- "1 " Job : has >
MS "1" - "1" Agenda : has >
MS "1    " - "*" GreenSpace: manages >
GSU"1" - "*" GreenSpace: uses >
GSM "1" - "*" GreenSpace: manages >

@enduml