@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class Organization {
    name
    vatNumber
    website
    phoneNumber
    email

}

class GreenSpace {
    size
}

class Garden
class MediumSizedPark
class LargeSizedPark

class SystemUser {
    name
    email
    password
    phone

}
class HRM {
}
class FM {
}
class Collaborator {
               birthdate
               admissionDate
               address
               idDocType
               idNumber
}
class GSM {
}
class GSU {
}

class TeamProposal {
}

class Team {
}

class Skill {
    name
}

class Job {
    name
}

class Task {
    description
    recurrency
}

class VehicleCheckup {
        vehicleID
        date
        currentKms
}

class Vehicle {
            brand
           model
           type
           tare
           gross
           weight
           currentKm
           registerDate
           acquisitionDate
           maintenance/checkupFrequency
}

class Machine {
    name
}

class Equipment {
    name
}

class Agenda {
}

class AgendaEntry {
    timeInterval
    date
}

class GreenSpacesUserPortal{
}

class Comment{
    description
}
class Report{
    description
}

class Category {
    description
}

class ToDoList{

}

class ListOfVehiclesNeedingCheckUp {
}


SystemUser --|> HRM
SystemUser --|> FM
SystemUser --|> Collaborator
SystemUser --|> GSM
SystemUser --|> GSU

GreenSpace --|> Garden
GreenSpace --|> MediumSizedPark
GreenSpace --|> LargeSizedPark

Task "1" -- "1..*" GreenSpace : occurs in >

Agenda "1" -- "*" AgendaEntry : has >
AgendaEntry "1" -- "1" Task : defines >
AgendaEntry "1" -- "1" Team : defines >

FM " 1" -- "0..*     " Vehicle : registers >
FM "  1 " -- "*" Machine : manages >
FM "  1    " -- "*" Equipment : manages >
Vehicle "1   " -- "0..* " VehicleCheckup : has >
FM "1 " -- "0..*  " VehicleCheckup : requests >
GSU"  1  " -- "0..*          " Report: makes >
GSU"  1  " -- "0..*   " Comment: makes >
GSU"  1  " -- "0..*   " GreenSpacesUserPortal:  uses >
GreenSpacesUserPortal "1                 " -- "0..*   " Report : has >
GreenSpacesUserPortal "1    " -- "0..*" Comment : has >

Organization "1" - "*" SystemUser : has >
Organization "1" - "0..*" Task: owns >
Task "1" - "1" Category: cataloged as >
Task "1" - "1  " Team:   carried out by   >
ToDoList "1" - "0..*" Task: contains >

HRM "1 " -- "*" Collaborator : creates >
HRM "1" -- "1  " TeamProposal : requests >
TeamProposal "1 " --"1        " Team: has >
Team "1 " -- "1..*  " Collaborator: has >
Collaborator "1 " -- "0..* " Skill : has >
Collaborator "1 " -- "1 " Job : has >
Organization "1" - "1" Agenda : has >
Organization "1" - "*" GreenSpace: manages >
GSU"1" - "*" GreenSpace: uses >
GSM "1" - "*" GreenSpace: manages >
ListOfVehiclesNeedingCheckUp "1" - "*" Vehicle : has >
@enduml