@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "VFM" as VFM
participant ":RegisterVehicleCheckupUI" as UI
participant "RegisterVehicleCheckupController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehicleRepository:\nVehicleRepository" as VehicleRepository
participant "vehicle:\nVehicle" as vehicle
participant "vehicleCheckup:\nVehicleCheckup" as checkup
activate VFM

        VFM -> UI : asks to register a vehicle check-up

        activate UI

'
            UI -> CTRL** : create
               activate CTRL
            CTRL -> RepositorySingleton : getInstance()
                            activate RepositorySingleton


                                RepositorySingleton --> CTRL: repositories
                            deactivate RepositorySingleton

                            CTRL -> PLAT : getVehicleRepository()
                            activate PLAT

                                PLAT --> CTRL: vehicleRepository
                            deactivate PLAT


            UI -> CTRL : getVehicles()



                CTRL -> VehicleRepository : getVehicles()
                activate VehicleRepository

                    VehicleRepository --> CTRL : vehiclesList
                deactivate VehicleRepository


                CTRL --> UI : vehiclesList
            deactivate CTRL

            UI --> VFM : shows available vehicles and asks to select one
        deactivate UI

    VFM -> UI : selects a vehicle
    activate UI

        UI --> VFM : requests date and currentKms
    deactivate UI

    VFM -> UI : types requested data
    activate UI



        UI -> CTRL : createVehicleCheckup(vehicle, date, currentKms)
        activate CTRL

        CTRL -> VehicleRepository : createVehicleCheckup(vehicle, date, currentKms)
activate  VehicleRepository

VehicleRepository -> checkup**: create(date, currentKms)
activate checkup
    checkup --> VehicleRepository: vehicleCheckup
deactivate checkup

VehicleRepository -> vehicle: addCheckup(checkup)
activate vehicle
    note bottom: adds checkup to checkupList \nand updates currentKms
deactivate vehicle
VehicleRepository--> CTRL: status of creation

deactivate VehicleRepository

CTRL --> UI : status of creation
deactivate CTRL
UI -->VFM : shows operation status
deactivate UI
deactivate VFM

@enduml