@startuml
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline

title Class Diagram

class ToDoEntry{
    greenSpace
    description
    urgencyDegree
    status
    expectedDuration
}

class AgendaEntry {
    date
    associatedTeam
    associatedVehicles
}

class AgendaEntryDTO {
    entryID
    description
    plannedDate
    status
}

class SystemUser {
    name
    email
    password
    phone
}

class ToDoEntryDTO {
    greenSpace
    description
    urgencyDegree
    status
    expectedDuration
}

class ToDoEntryRepository {
    - ArrayList<ToDoEntry> toDoEntries
    + getToDoEntryListByStatus(email, status)
}

class AgendaEntryRepository {
    - ArrayList<AgendaEntry> agendaEntries
    + getAgendaEntries()
    + addEntryToAgenda(AgendaEntry)
}

class Repositories {
    - agendaEntryRepository
    - toDoEntryRepository

    - Repositories()
    + getInstance()
    + getAgendaEntryRepository()
    + getToDoEntryRepository()
}

class AgendaEntryMapper {
    + toDTO(agendaEntry)
    + toEntity(agendaEntryDTO)
    + toDTOList(List<AgendaEntry>)
}

class ToDoEntryMapper {
    + toDTO(toDoEntry)
    + toEntity(toDoDTO)
    + toDTOList(List<ToDoEntry>)
}

class RegisterAgendaEntryGUIController {
    - AgendaEntryRepository agendaEntryRepository
    - ToDoEntryRepository toDoEntryRepository
    - AgendaEntryMapper agendaEntryMapper
    - ToDoEntryMapper toDoEntryMapper
    + getAvailableToDoEntries(event)
    + registerAgendaEntry(event)
    + closeWindow(event)
    + setAgendaMenuGUIController(AgendaMenuGUIController\n agendaListGUIController)
}

class AgendaGUI {
    - RegisterAgendaEntryGUIController agendaController
    + openRegisterAgendaEntryWindow(event)
}

AgendaGUI .> RegisterAgendaEntryGUIController
RegisterAgendaEntryGUIController ..> Repositories : repositories
Repositories --> "1" AgendaEntryRepository
Repositories --> "1" ToDoEntryRepository
Repositories -> Repositories : instance
RegisterAgendaEntryGUIController .> AgendaEntryMapper
RegisterAgendaEntryGUIController .> ToDoEntryMapper
RegisterAgendaEntryGUIController --> AgendaEntryRepository : uses
RegisterAgendaEntryGUIController --> ToDoEntryRepository : uses

SystemUser <|- GSM
ToDoEntry <|-- AgendaEntry

GSM  -- AgendaGUI
AgendaEntryMapper "1"-> "*" AgendaEntry : creates
AgendaEntry "*" <-- "1" AgendaEntryRepository : stores
AgendaEntryDTO "*" <-- "1" AgendaEntryMapper : creates
ToDoEntryDTO "*" <-- "1" ToDoEntryMapper : creates

@enduml
