@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "GSM" as Employee
participant ":PostponeAgendaEntryGUI" as UI
participant "AgendaEntryDTO"

activate Employee

    Employee -> UI : selects an entry
    activate UI

        UI --> Employee : asks to select a new date
    deactivate UI

    Employee -> UI : selects new date for the entry
    activate UI

        UI -> "AgendaEntryDTO" : agendaEntryDTO.date = newDate
        activate "AgendaEntryDTO"
        deactivate "AgendaEntryDTO"

deactivate UI
deactivate Employee
@enduml
