\@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



skinparam classAttributeIconSize 0

hide circle
hide methods


class SystemUser {
    name
    email
    password
    phone

}
class GSM {

}

class AgendaEntry {
    date
    associatedTeam
    associatedVehicleList
}


class ToDoEntry{
    description
         greenSpace
         expectedDuration
         degreeUrgency
         entryStatus
}


GSM "1" - "*" AgendaEntry : postpones >
SystemUser <|- GSM
AgendaEntry --|> ToDoEntry


@enduml