@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



skinparam classAttributeIconSize 0

hide circle
hide methods


class GSM {
}


class SystemUser {
    name
    email
    password
    phone

}

class Collaborator {
   name
      phone
      birthdate
      admissionDate
      address
      idDocumentType
      idDocumentNumber
      status
      }



class Team {
minimumSize
maximumSize

}

class Skill {
    name
}


class Agenda {
}

class AgendaEntry {

    timeInterval
    date
}


class Task {
    description
    recurrency
    duration
}


Team "1 " -- "*" Collaborator: has >
Team "1 " -- "*" Skill : has >
Collaborator "1 " - "0..* " Skill : has >
SystemUser <|- GSM
GSM"1" - "*" AgendaEntry: adds >
AgendaEntry"1"-- "1  " Team: assigned to >
Agenda "1" -- "*" AgendaEntry : has >
AgendaEntry "1" -- "1  " Task : defines >
Team "1" - "*" Task:   carries  >

@enduml