@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



skinparam classAttributeIconSize 0

hide circle
hide methods


class GSM {
}


class SystemUser {
    name
    email
    password
    phone

}

class Team {
minimumSize
maximumSize

}

class Agenda {
}

class AgendaEntry {
    date
    associatedTeam
    associatedVehicleList
}




class ToDoEntry{
    description
         greenSpace
         expectedDuration
         degreeUrgency
         entryStatus
}





SystemUser <|- GSM
GSM"1" - "*" AgendaEntry: manages >
AgendaEntry"1"-- "1  " Team: assigned to >
Agenda "1" -- "*" AgendaEntry : has >
AgendaEntry --|> ToDoEntry



@enduml