@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



skinparam classAttributeIconSize 0

hide circle
hide methods

class VFM {

}

class VehicleCheckup {
vehicleID
    currentKms
    date

}

class Vehicle {

        brand
        model
        vehicleID
        type
        tare
        grossWeight
        currentKm
        registerDate
        acquisitionDate
        checkupFrequency
}


VFM "1" -- "0..*   " Vehicle : registers >
Vehicle "1   " -- "0..*                        " VehicleCheckup : has >
VFM "           1 " -- "0..*   " VehicleCheckup : requests >

@enduml