@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "GSM" as ADM
participant ":GreenSpaceUI" as UI
participant "ListGreenSpacesController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "greenSpaceRepository:\n GreenSpaceRepository" as Repo
participant "GreenSpaceMapper"
participant "GreenSpaceDTO" as GreenSpaceDTO

activate ADM

        ADM -> UI : asks to list the green spaces

        activate UI
            UI -> CTRL** : create

            UI -> CTRL : getGreenSpaceDTOsList()
            activate CTRL

            CTRL->  "GreenSpaceMapper"**: create

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getGreenSpaceRepository()
                activate PLAT

                    PLAT --> CTRL: greenSpaceRepository()
                deactivate PLAT

                CTRL -> Repo : getGreenSpaceList(authenticationController.getCurrentUserEmail())
                activate Repo


                    Repo --> CTRL : greenSpaceListGSM
                deactivate Repo

                CTRL --> "GreenSpaceMapper" : toDTOList(greenSpaceListGSM)
                activate "GreenSpaceMapper"

                 loop for each greenSpace in greenSpaceList

                                 "GreenSpaceMapper" -> "GreenSpaceDTO"** : GreenSpaceDTO = toDTO(greenSpace)


                                  end
            deactivate CTRL

            "GreenSpaceMapper"--> CTRL: greenSpaceDTOsList
            deactivate "GreenSpaceMapper"
            activate CTRL

            CTRL-->     UI: greenSpaceDTOsList
            deactivate CTRL

            UI-> CTRL: sortGreenSpaces(greenSpaceDTOsList)
            activate CTRL

            CTRL-> AplicationSession: getSortingAlgorithm()
                        note right: goes to the config file and gets the property of the to be\n used algorithm and then sorts the list through interface


            UI--> ADM: sorted green spaces list
        deactivate UI


deactivate ADM

@enduml