@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "GSM" as ADM
participant ":GreenSpaceUI" as UI
participant "ListGreenSpacesController" as CTRL

activate ADM

ADM -> UI : asks to list the green spaces
activate UI

UI -> CTRL : create
activate CTRL

deactivate ADM

@enduml
