@startuml
actor "VFM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to register a vehicle for inspection
    activate System

        System --> Employee :  shows the vehicles registered
    deactivate System

    Employee -> System : selects a vehicle for check-up
    activate System

 System --> Employee :  requests data (date, current kms)
    deactivate System

    Employee -> System : types requested data
    activate System

        System --> Employee : displays operation success
    deactivate System
@enduml