@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "GSM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to add vehicles to an entry in the agenda
    activate System

        System --> Employee :shows list of entries and the list of vehicles
    deactivate System

     Employee -> System : chooses an entry and vehicles from list to add
        activate System



            System --> Employee : displays operation success
                deactivate System





@enduml