@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "GSM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to add a new entry from the "To Do List"\n to the Agend
    activate System

        System --> Employee : displays the "To Do List" entries that are\n not in the Agenda
    deactivate System

    Employee -> System : selects the desired entry
        activate System

            System --> Employee : asks for a date for the entry on the Agenda
        deactivate System

        Employee -> System : selects date for the entry
            activate System

                    System --> Employee : displays message of (in)success
                deactivate System


@enduml