@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



skinparam classAttributeIconSize 0

hide circle
hide methods


class SystemUser {
    name
    email
    password
    phone

}
class Collaborator {
    name
    phone
    birthdate
    admissionDate
    address
    idDocumentType
    idDocumentNumber
    status
}


class AgendaEntry {
    date
    associatedTeam
    associatedVehicleList
}


class ToDoEntry{
    description
         greenSpace
         expectedDuration
         degreeUrgency
         entryStatus
}



Collaborator "1" - "*" AgendaEntry:   carries  >
SystemUser <|- Collaborator
AgendaEntry --|> ToDoEntry
@enduml