@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "FM" as ADM
participant ":ListVehivclesCheckupsUI" as UI
participant ":ListVehivclesCheckupsController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehiclesRepository:\nVehiclesRepository" as TaskCategoryRepository


activate ADM

        ADM -> UI : asks to list the vehicles that need the check-up.

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getVehicles()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getVehiclesRepository()
                activate PLAT

                    PLAT --> CTRL: VehiclesRepository()
                deactivate PLAT

                CTRL -> TaskCategoryRepository : getVehicles()
                activate TaskCategoryRepository

                    TaskCategoryRepository --> CTRL : VehiclesList
                deactivate TaskCategoryRepository

                CTRL --> UI : VehiclesList
            deactivate CTRL

            UI --> ADM : shows Vehicles list
        deactivate UI


deactivate ADM

@enduml