@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods


class Skill {
    Name
}

class HRM {
    name
    ID
}


HRM "1" - "0..*" Skill : creates >

@enduml