@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "GSM" as GSM
participant ":AgendaEntryUI" as UI
participant ":CancelAgendaEntryController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "agendaEntryRepository:\nAgendaEntryRepository" as Repo
participant "AgendaEntryMapper"
participant "AgendaEntryDTO"
participant "AgendaEntry"


activate GSM

                GSM -> UI : asks to cancel an entry on the Agenda

                activate UI

                UI -> CTRL** : create
                activate CTRL
                CTRL-> "AgendaEntryMapper"** : create



                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton


                CTRL -> PLAT : getAgendaEntryRepository()
                activate PLAT

                    PLAT --> CTRL: AgendaEntryRepository()
                deactivate PLAT

                UI-> CTRL: getAgendaEntryDTOList()


                CTRL -> Repo : getAgendaEntryList()
                activate Repo

                Repo --> CTRL: agendaEntryList
                deactivate Repo




                CTRL -> "AgendaEntryMapper" : toDtoList(agendaEntryList)
                activate "AgendaEntryMapper"


                 loop for each agendaEntry in agendaEntryList

                 "AgendaEntryMapper" -> "AgendaEntryDTO" : agendaEntryDTO = toDTO(agendaEntry)

                  activate "AgendaEntryDTO"
                  end
                deactivate "AgendaEntryDTO"

                "AgendaEntryMapper" --> CTRL : agendaEntryDTOList
                deactivate "AgendaEntryMapper"

                 CTRL --> UI : agendaEntryDTOList
                 deactivate CTRL

                  UI --> GSM : shows the list of entries in the Agenda\n and asks to select one


                 GSM-> UI: selects an entry

                 UI-> CTRL: cancelsEntry(AgendaEntry)
                activate CTRL
                CTRL-> "AgendaEntryMapper":toEntity(agendaEntryDTO)
                activate "AgendaEntryMapper"
                 "AgendaEntryMapper" -> "AgendaEntry": agendaEntry = toEntity(agendaEntryDTO)
                 activate "AgendaEntry"
                 AgendaEntry-->"AgendaEntryMapper": agendaEntry




                "AgendaEntryMapper"-->CTRL: agendaEntry
                deactivate "AgendaEntry"
                deactivate "AgendaEntryMapper"

                CTRL-> "AgendaEntry": cancelsEntry(agendaEntry)


                CTRL-> Repo: update(agendaEntry)
                activate Repo
                deactivate "AgendaEntry"
              deactivate Repo

                CTRL --> UI : success/insuccess
                deactivate CTRL
               UI --> GSM : shows (in)success message
               deactivate UI


deactivate GSM

@enduml