@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor " HRM" as ADM
participant ":RegisterVehicleUI" as UI
participant ":RegisterVehicleController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehicleRepository:\nVehicleRepository" as VehicleRepository

activate ADM

        ADM -> UI : asks to register a new job

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL


            UI --> ADM : requests data
        deactivate UI

    ADM -> UI : types requested data (job name)
    activate UI

        UI --> ADM : requests confirmation
    deactivate UI

    ADM -> UI : confirms
    activate UI

        UI -> CTRL : createVehicle(brand, model, vehicleID, type, tare,\n grossWeight, currentKm, registerDate,\n acquisitionDate, checkupFrequency)
        activate CTRL


                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getVehicleRepository()
                activate PLAT

                    PLAT --> CTRL : vehicleRepository
                deactivate PLAT

                CTRL -> VehicleRepository : createVehicle(brand, model, vehicleID, type, tare,\n grossWeight, currentKm, registerDate,\n acquisitionDate, checkupFrequency)
                activate VehicleRepository

                VehicleRepository -> VehicleRepository : validateVehicle(vehicleID)
                activate VehicleRepository
                deactivate VehicleRepository


                    VehicleRepository --> CTRL : status of creation
                deactivate VehicleRepository
                    CTRL --> UI : status of creation
                    UI --> ADM : shows operation status
                    deactivate UI
            deactivate CTRL



@enduml