@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}


class vehicle
 {
   Brand
   Model
   Type
   Tare
   Gross
   Weight
   Current Km
   Register Date
   Acquisition Date
   Maintenance/Checkup
   Frequency
}
'class User {
'    name
'    email
'    password
'}

class FM{
  name
  id
}


FM "1" - "1..*" vehicle: creates a >
@enduml