@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Collaborator" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to mark a task as completed
    activate System

        System --> Employee : validate task
    deactivate System

        Employee -> System : Record completion date and time
        activate System

            System --> Employee :Confirm task completion
        deactivate System


@enduml