@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Collaborator" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to mark a task as completed
    activate System

        System --> Employee : show the list of entries
    deactivate System

        Employee -> System : choose an entry and marks as completed
        activate System

            System --> Employee :Confirm task completion
        deactivate System


@enduml