@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class Organization {
    name
    vatNumber
    website
    phoneNumber
    email
}

class Collaborator {
    name
    birthday
    admission date
    address
    cellphone number
    e-mail
    ID number
}


class HRM {
    name
    email
    position
    phone
}


class Job{
    name
}

'Platform "1" -- "*" Organization : has registered >
'Platform "1" -- "*" Category : defines >
Organization "1" - "1" HRM : has >
'Task "*" -- "1" HRM: created by >
HRM "1" -- "*" Collaborator : creates >
HRM "1" -- "*" Job : creates >
'HRM "0..1" -- "1" User: acts as >
Collaborator "1" -- "1" Job : has >

@enduml