@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "GSM" as GSM
participant ":AgendaEntryUI" as ui
participant "AssignVehicles" as ctrl
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as plat
participant "agendaEntryRepository:\nAgendaEntryRepository" as agendaRepo
participant "AgendaEntryMapper" as agendaMapper
participant AgendaEntryDTO as AgendaEntryDTO
participant "AgendaEntry" as agendaEntry
participant "Vehicle" as vehicle
participant "vehicleRepository:\nVehicleRepository" as vehicleRepo
participant "VehicleMapper" as VehicleMapper
participant "VehicleDTO" as VehicleDTO
participant "ApplicationSession" as app

activate GSM

GSM -> ui : asks to assign vehicles to an agenda entry
activate ui

ui -> ctrl : create
activate ctrl

ctrl -> agendaMapper : create

ctrl -> RepositorySingleton : getInstance()
activate RepositorySingleton
RepositorySingleton --> ctrl: repositories
deactivate RepositorySingleton

ctrl -> plat : getAgendaEntryRepository()
activate plat
plat --> ctrl: AgendaEntryRepository()
deactivate plat

ctrl -> plat : getVehicleRepository()
activate plat
plat --> ctrl: vehicleRepository
deactivate plat

ui -> ctrl : getAgendaEntriesDTOWithoutVehicles()
ui -> ctrl : showVehiclesDTO()

ctrl -> agendaRepo : getAgendaEntryListWithoutVehicles()
activate agendaRepo
agendaRepo --> ctrl: agendaEntryList
deactivate agendaRepo


ctrl -> agendaMapper : toDtoList(agendaEntryList)
activate agendaMapper


loop for each agendaEntry in agendaEntryList
  agendaMapper -> AgendaEntryDTO : agendaEntryDTO = toDTO(agendaEntry)
  activate AgendaEntryDTO
end

agendaMapper --> ctrl : agendaEntryDTOList
deactivate agendaMapper
deactivate AgendaEntryDTO

ctrl -> vehicleRepo : getVehicles()
activate vehicleRepo
vehicleRepo --> ctrl: vehicles
deactivate vehicleRepo

ctrl -> VehicleMapper : toDtoList(vehicles)
activate VehicleMapper
loop for each vehicle in vehicles
  VehicleMapper -> VehicleDTO : vehicleDTO = toDTO(vehicle)
  activate VehicleDTO
end
deactivate VehicleDTO
VehicleMapper --> ctrl : vehicleDTOList
deactivate VehicleMapper

ctrl --> ui : agendaEntryDTOList
ctrl --> ui : vehicleDTOList
deactivate ctrl

ui --> GSM : shows the list of entries in the agenda\n and the list of vehicles and asks to select one of each

GSM -> ui : selects entry and vehicles

ui -> ctrl : assignVehiclesToAgendaEntry(selectedEntry, selectedVehicles)
activate ctrl

ctrl -> agendaRepo : getAgendaEntry(selectedEntry.description, selectedEntry.greenSpace)
activate agendaRepo
agendaRepo --> ctrl : agendaEntry
deactivate agendaRepo

ctrl -> vehicleRepo : getVehicles(selectedVehicles)
activate vehicleRepo
vehicleRepo --> ctrl : vehicles
deactivate vehicleRepo

ctrl -> agendaEntry : setAssociatedVehicles(vehicles)
activate agendaEntry
deactivate agendaEntry

ctrl -> agendaRepo : save(agendaEntry)
activate agendaRepo
agendaRepo --> ctrl : success/insuccess
deactivate agendaRepo

ctrl --> ui : success/insuccess
deactivate ctrl

ui --> GSM : shows (in)success message
deactivate ui

deactivate GSM

@enduml
