@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "GSM" as GSM
participant ":AssignVehiclesUI" as ui
participant "AssignVehiclesController" as ctrl
participant "agendaEntryRepository:\nAgendaEntryRepository" as agendaRepo
participant "AgendaEntryMapper" as agendaMapper
participant AgendaEntryDTO as AgendaEntryDTO
participant "Vehicle" as vehicle
participant "vehicleRepository:\nVehicleRepository" as vehicleRepo
participant "VehicleMapper" as VehicleMapper
participant "VehicleDTO" as VehicleDTO

activate GSM

ui -> ctrl : getAgendaEntriesDTOWithoutVehicles()
ui -> ctrl : showVehiclesDTO()

ctrl -> agendaRepo : getAgendaEntryList()
activate agendaRepo
agendaRepo --> ctrl: agendaEntryList
deactivate agendaRepo

ctrl -> agendaMapper : toDtoList(agendaEntryList)
activate agendaMapper

loop for each agendaEntry in agendaEntryList
  agendaMapper -> AgendaEntryDTO : agendaEntryDTO = toDTO(agendaEntry)
  activate AgendaEntryDTO
end

agendaMapper --> ctrl : agendaEntryDTOList
deactivate agendaMapper
deactivate AgendaEntryDTO

ctrl -> vehicleRepo : getVehicles()
activate vehicleRepo
vehicleRepo --> ctrl: vehicles
deactivate vehicleRepo

ctrl -> VehicleMapper : getVehiclesListDTO(vehicles)
activate VehicleMapper
loop for each vehicle in vehicles
  VehicleMapper -> VehicleDTO : vehicleDTO = toDTO(vehicle)
  activate VehicleDTO
end
deactivate VehicleDTO
VehicleMapper --> ctrl : vehicleDTOList
deactivate VehicleMapper

ctrl --> ui : agendaEntryDTOList
ctrl --> ui : vehicleDTOList
deactivate ctrl

ui --> GSM : shows the list of entries in the agenda\n and the list of vehicles and asks to select one of each

deactivate ui
deactivate GSM

@enduml
