@startuml
skinparam monochrome true
skinparam packageStyle rectangle
    skinparam shadowing false

    autonumber

    'hide footbox
    actor "GSM" as HRM
    participant ":AssignVehiclesUI" as UI
    participant ":AssignVehiclesController" as CTRL
    participant ":Repositories" as RepositorySingleton
    participant "repositories\n:Repositories" as PLAT
    participant "vehicleRepository:\nVehicleRepository" as SkillRepository
    participant "entryRepository:\nEntryRepository" as entryRepository
    activate HRM

            HRM -> UI : asks to add vehicles to an entry in the agenda

            activate UI

    '            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
                'create CTRL
                UI -> CTRL** : create

                UI -> CTRL : getEntries()
                activate CTRL

                    CTRL -> RepositorySingleton : getInstance()
                    activate RepositorySingleton

                        RepositorySingleton --> CTRL: repositories
                    deactivate RepositorySingleton

                    CTRL -> PLAT : getEntryRepository()
                    activate PLAT

                        PLAT --> CTRL: entryRepository
                    deactivate PLAT

                    CTRL -> entryRepository : getEntry()
                    activate entryRepository

                        entryRepository--> CTRL : entriesList
                    deactivate entryRepository

                    CTRL --> UI : entriesList






           UI -> CTRL : getVehicles()

                 CTRL -> RepositorySingleton : getInstance()
                 activate RepositorySingleton
                   RepositorySingleton -> CTRL : repositories
                 deactivate RepositorySingleton

                 CTRL -> PLAT : getVehicleRepository()
                 activate PLAT
                   PLAT --> CTRL : vehicleRepository
                 deactivate PLAT

                 CTRL -> SkillRepository : getVehicles()
                 activate SkillRepository
                   SkillRepository --> CTRL : vehiclesList
                 deactivate SkillRepository
                 CTRL --> UI :vehiclesList
               deactivate CTRL

              UI --> HRM : shows list of entries and the list of vehicles \nand asks to select a entry
                          deactivate UI

             HRM -> UI : chooses an entry

             activate UI
              HRM -> UI : chooses vehicles from list to add
               UI -> CTRL :assignVehicles(entries,vehicles)
                        activate CTRL
               CTRL -> RepositorySingleton : getInstance()
                                         activate RepositorySingleton
                                           RepositorySingleton -> CTRL : repositories
                                         deactivate RepositorySingleton

                                         CTRL -> PLAT : getEntryRepository(entry,vehicles)
                                         activate PLAT
                                           PLAT --> CTRL : entryRepository
                                         deactivate PLAT

                                         CTRL -> entryRepository : assignVehicles()
                                       activate entryRepository
                                           entryRepository --> CTRL : List of entry's current vehicles
                                   deactivate entryRepository
                                         CTRL --> UI : List of entry's current vehicles
                                       deactivate CTRL
                                       UI --> HRM :Show list of entry's current vehicles
                                                    deactivate UI





    deactivate HRM

@endumlenduml