@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US005

autonumber

actor "HRM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to generate a team proposal
    activate System

        System --> Employee : requests data (number of desired employees, team members skills)
    deactivate System

    Employee -> System : types data
    activate System

        System --> Employee : shows all data and requests confirmation or modification
    deactivate System

    Employee -> System : modifies data
    activate System

        System --> Employee : shows all data and requests confirmation or modification

       Employee -> System : confirms data
        activate System

            System --> Employee : displays operation success
        deactivate System



@enduml